 spring:
   datasource:
     # url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:2345}/${DB_NAME:test}
     url: jdbc:postgresql://localhost:5432/loay
     username: postgres
     password: postgres
     driver-class-name: org.postgresql.Driver
   jpa:
     hibernate:
       ddl-auto: none
       jdbc:
         lob:
           non_contextual_creation: true
     show-sql: true
 server:
   port: 8787
